### PR TITLE
Change URL to use a variable

### PR DESCRIPTION
**Pull request by Blake-**
We've had others ask about using this plugin, changing up that URL to use something like plugin.help.url from the yml would make this flexible enough to use on any site. This could then be moved to the other en.yml files to use on any sites
```
en:
  plugin:
    help:
      text: Ask The Archives A Question
      url: https://www.example.org/Ask-the-Archivist
```

### CODE REVIEW

**Comment by Blake-** [comment]
Hi All, any thoughts on this?

**Comment by Blake-** [comment]
Hi All, any thoughts on this?

**Comment by triplingual** [comment]
Sorry about the delay!

1) Note that while putting a URL in the YML would take care of part of the eventual target URL, there's a lot getting passed in the querystring. Users of the plugin will still need to consider whether the right stuff is getting passed. Without rewriting this from scratch, we couldn't construct the querystring in a YML or config file, because . . .
2) There's a dependency on jQuery reading a particular CSS architecture. If someone doesn't have that or doesn't have the capability to mod the plugin, it might not work.

If those aren't barriers to the use case(s) you  have in mind, I'll move forward with this.

**Comment by Blake-** [comment]
Thanks Trip! It looks like that won't quite work for what we had in mind. I'll close this and write something else!

**Pull request closed without merging**
